In [ ]:

import pandas as pd
import glob
df = pd.read_csv("ap_bus_details.csv")
df = pd.read_csv("assam_bus_details.csv")
df = pd.read_csv("chandigarh_bus_details.csv")
df = pd.read_csv("himachal_bus_details.csv")
df = pd.read_csv("kadamba_bus_details.csv")
df = pd.read_csv("kerala_bus_details.csv")
df = pd.read_csv("rajasthan_bus_details.csv")
df = pd.read_csv("Southbengal_bus_details.csv")
df = pd.read_csv("Telangana_bus_details.csv")
df = pd.read_csv("up_bus_details.csv")
df = pd.read_csv("wb_bus_details.csv")
df = pd.read_csv("jk_bus_details.csv")

# List of CSV file paths
csv_files = ["ap_bus_details.csv", "assam_bus_details.csv", "chandigarh_bus_details.csv", "himachal_bus_details.csv", "kadamba_bus_details.csv", "kerala_bus_details.csv","rajasthan_bus_details.csv", "Southbengal_bus_details.csv", "Telangana_bus_details.csv", "up_bus_details.csv", "wb_bus_details.csv",  "jk_bus_details.csv"]   

# Read each CSV file into a DataFrame and store it in a list
df = [pd.read_csv(file) for file in csv_files]

# Concatenate all DataFrames in the list
combined_df = pd.concat(df, ignore_index=True)

combined_df.to_csv("bus_routes.csv", index=False)

#add id column
id_column = pd.Series(range(1, len(df) + 1), name='id')
df = pd.concat([id_column, df], axis=1)
df = pd.read_csv("bus_routes.csv")

# replace string to empty string
df['Price'] = df['Price'].str.replace('INR ', '')

#extract the digits(0-9)
df['Seat_Availability'] = df['Seat_Availability'].str.extract('(\d+)')

#python mysql connection
import pymysql
myconnection = pymysql.connect(host='127.0.0.1', user='root',passwd='12345678',database="redbus")
df = pd.read_csv("bus_routes.csv")
df = df.dropna() #drop null values
a = ",".join(f"{i} {j}"
for i,j in zip(df.columns,df.dtypes)).replace("float64","float").replace("object","text").replace("int64","int") #replace dtypes from pandas to mysql
table_name = "bus_routes"
myconnection.cursor().execute(f"create table {table_name} ({a})")
for i in range(len(df)):
    myconnection.cursor().execute(f"insert into {table_name} values {tuple(df.iloc[i])}")
    myconnection.commit()

In [30]:
df=pd.read_csv(r"C:\Users\pavelkannan\Guvi\Redbus_Project\bus_routes.csv")
df

,ID,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9356,Super Luxury (Non AC Seater 2+2 Push Back),11:30,06h 35m,18:05,4.0,INR 469,31 Seats available
1,2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3858,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),11:30,05h 00m,16:30,3.7,INR 670,44 Seats available
2,3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35269,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),12:15,06h 10m,18:25,3.7,INR 720,24 Seats available
3,4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3601,Super Luxury (Non AC Seater 2+2 Push Back),12:30,08h 05m,20:35,2.5,INR 469,31 Seats available
4,5,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3515,Super Luxury (Non AC Seater 2+2 Push Back),13:00,08h 00m,21:00,2.0,INR 469,31 Seats available
...,...,...,...,...,...,...,...,...,...,...,...
7678,7679,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Vijay Tour and Travels,Bharat Benz A/C Seater /Sleeper (2+1),17:15,04h 35m,21:50,2.2,509,14 Seats available
7679,7680,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Vijay Tour and Travels,Bharat Benz A/C Seater /Sleeper (2+1),18:50,04h 50m,23:40,2.2,555,6 Seats available
7680,7681,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Lucky Travels,Bharat Benz A/C Seater / Sleeper (2+2),23:55,05h 35m,05:30,2.0,INR 279,39 Seats available
7681,7682,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Gajraj bus service,Bharat Benz A/C Sleeper (2+1),18:30,05h 25m,23:55,3.9,INR 899,20 Seats available
7682,7683,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Neeraj travels,A/C Seater / Sleeper (2+1),15:40,04h 32m,20:12,2.5,854,26 Seats available