In [ ]:
#Connecting Pandas to MySQL

In [9]:
import pandas as pd
import pymysql

# Database connection
myconnection = pymysql.connect(
    host='127.0.0.1',
    user='root',
    passwd='12345678',
    database='Redbus_Project'
)

# Read and clean CSV data
df = pd.read_csv("bus_routes.csv")
df = df.dropna()  # Drop rows with null values

# Convert pandas dtypes to MySQL types
dtype_mapping = {
    'float64': 'FLOAT',
    'object': 'TEXT',
    'int64': 'INT'
}
column_definitions = ", ".join(
    f"{col} {dtype_mapping[str(dtype)]}" 
    for col, dtype in zip(df.columns, df.dtypes)
)

# Table name
table_name = "Busroutes"

# Create table if it does not exist
with myconnection.cursor() as cursor:
    cursor.execute(f"CREATE TABLE IF NOT EXISTS {table_name} ({column_definitions})")

# Insert data into table
insert_query = f"INSERT INTO {table_name} ({', '.join(df.columns)}) VALUES ({', '.join(['%s'] * len(df.columns))})"
with myconnection.cursor() as cursor:
    cursor.executemany(insert_query, df.values.tolist())
    myconnection.commit()

# Close the connection
myconnection.close()

print("Data inserted successfully")

Data inserted successfully

In [10]:
result=pd.read_csv("bus_routes.csv")
result

,ID,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 9356,Super Luxury (Non AC Seater 2+2 Push Back),11:30,06h 35m,18:05,4.0,INR 469,31 Seats available
1,2,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3858,DOLPHIN CRUISE (VOLVO / SCANIA A.C Multi Axle),11:30,05h 00m,16:30,3.7,INR 670,44 Seats available
2,3,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 35269,AMARAVATHI (VOLVO / SCANIA A.C Multi Axle),12:15,06h 10m,18:25,3.7,INR 720,24 Seats available
3,4,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3601,Super Luxury (Non AC Seater 2+2 Push Back),12:30,08h 05m,20:35,2.5,INR 469,31 Seats available
4,5,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...,APSRTC - 3515,Super Luxury (Non AC Seater 2+2 Push Back),13:00,08h 00m,21:00,2.0,INR 469,31 Seats available
...,...,...,...,...,...,...,...,...,...,...,...
7678,7679,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Vijay Tour and Travels,Bharat Benz A/C Seater /Sleeper (2+1),17:15,04h 35m,21:50,2.2,509,14 Seats available
7679,7680,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Vijay Tour and Travels,Bharat Benz A/C Seater /Sleeper (2+1),18:50,04h 50m,23:40,2.2,555,6 Seats available
7680,7681,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Lucky Travels,Bharat Benz A/C Seater / Sleeper (2+2),23:55,05h 35m,05:30,2.0,INR 279,39 Seats available
7681,7682,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Gajraj bus service,Bharat Benz A/C Sleeper (2+1),18:30,05h 25m,23:55,3.9,INR 899,20 Seats available
7682,7683,Jammu (j and k) to Amritsar,https://www.redbus.in/bus-tickets/jammu-to-amr...,Neeraj travels,A/C Seater / Sleeper (2+1),15:40,04h 32m,20:12,2.5,854,26 Seats available